import { z } from "zod";

export const fileManagerFolderSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  description: z.string(),
  fileCount: z.number().int().nonnegative(),
  size: z.string(),
  updatedAt: z.string(),
  deletable: z.boolean(),
});

export const fileManagerFileSchema = z.object({
  id: z.string().min(1),
  folderId: z.string().min(1),
  name: z.string().min(1),
  kind: z.enum(["document", "spreadsheet", "image", "pdf", "archive"]),
  size: z.string(),
  owner: z.string(),
  ownerInitials: z.string(),
  modifiedAt: z.string(),
  shared: z.boolean(),
  starred: z.boolean(),
  contractId: z.string().optional(),
});

export const documentManagerStateSchema = z.object({
  version: z.literal(1),
  legacyMigrationComplete: z.boolean().default(false),
  folders: z.array(fileManagerFolderSchema),
  files: z.array(fileManagerFileSchema),
});

export type DocumentManagerState = z.infer<typeof documentManagerStateSchema>;

export const vanRecordSchema = z.object({
  id: z.string().min(1),
  registrationNumber: z.string(),
  vin: z.string(),
  make: z.string(),
  model: z.string(),
  manufactureYear: z.number().int(),
  colour: z.string(),
  fuelType: z.enum(["diesel", "petrol", "electric", "hybrid"]),
  transmission: z.enum(["manual", "automatic"]),
  mileage: z.number().nonnegative(),
  status: z.enum(["active", "available", "maintenance", "off_road", "returned"]),
  depot: z.string(),
  ownershipType: z.enum(["company_owned", "rented"]),
  ownerName: z.string(),
  purchaseDate: z.string().nullable(),
  purchasePrice: z.number().nullable(),
  rentalSupplier: z.string().nullable(),
  rentalContractNumber: z.string().nullable(),
  rentalStartDate: z.string().nullable(),
  rentalTerminationDate: z.string().nullable(),
  rentalMonthlyCost: z.number().nullable(),
  currentAssigneeId: z.string().nullable(),
  currentAssigneeName: z.string().nullable(),
  assignmentStartDate: z.string().nullable(),
  assignmentExpectedEndDate: z.string().nullable(),
  motExpiryDate: z.string().nullable(),
  motStatus: z.enum(["valid", "failed", "pending", "exempt"]),
  roadTaxExpiryDate: z.string().nullable(),
  roadTaxStatus: z.enum(["taxed", "due", "expired", "exempt"]),
  insuranceExpiryDate: z.string().nullable(),
  serviceDueDate: z.string().nullable(),
  serviceDueMileage: z.number().nullable(),
  lastInspectionDate: z.string().nullable(),
  nextInspectionDate: z.string().nullable(),
  documentCount: z.number().int().nonnegative(),
  notes: z.string(),
  createdAt: z.string(),
  createdBy: z.string(),
  updatedAt: z.string(),
  updatedBy: z.string(),
  archivedAt: z.string().nullable(),
  archivedBy: z.string().nullable(),
});

export const vanDataSchema = z.object({
  version: z.literal(1),
  vans: z.array(vanRecordSchema),
});

export const driverRecordSchema = z.object({
  id: z.string().min(1),
  firstName: z.string(),
  lastName: z.string(),
  preferredName: z.string(),
  dateOfBirth: z.string(),
  phone: z.string(),
  email: z.string(),
  address: z.string(),
  postcode: z.string(),
  employmentType: z.enum(["employee", "contractor", "agency"]),
  jobTitle: z.string(),
  status: z.enum(["active", "on_leave", "inactive"]),
  startDate: z.string(),
  endDate: z.string(),
  depot: z.string(),
  manager: z.string(),
  licenceNumber: z.string(),
  licenceCategories: z.string(),
  licenceExpiry: z.string(),
  licencePoints: z.number().int().nonnegative(),
  vehicleId: z.string(),
  vehicleRegistration: z.string(),
  vehicleAssignedDate: z.string(),
  rightToWorkExpiry: z.string(),
  dbsExpiry: z.string(),
  medicalExpiry: z.string(),
  complianceStatus: z.enum(["compliant", "action_required", "expired"]),
  emergencyContactName: z.string(),
  emergencyContactRelationship: z.string(),
  emergencyContactPhone: z.string(),
  usualRoute: z.string(),
  shiftPattern: z.string(),
  payrollReference: z.string(),
  notes: z.string(),
  createdAt: z.string(),
  createdBy: z.string(),
  updatedAt: z.string(),
  updatedBy: z.string(),
  deletedAt: z.string().nullable(),
  deletedBy: z.string(),
});

export const driverDataSchema = z.object({
  version: z.literal(1),
  drivers: z.array(driverRecordSchema),
});
